version: '2'

services:
    app:
        build: ./app
        image: versive/aws-cloudwatch-metrics:latest

        volumes:
            - ~/.aws:/root/.aws:ro
            - ~/.boto:/root/.boto:ro
            - ./app/src:/usr/src/app/src:ro
            - ./app/output:/usr/src/app/output
